package com.yinzhiwu.yiwu.event;

/**
 * 
 * @author ping
 * @Date 2017年10月29日 下午5:16:03
 *
 */
public enum IncomeEventType {
	
	REGISTER_WITHOUT_INVATATION_CODE,
	REGISTER_WITH_INVATATION_CODE,
	SHARE_TWEET_BY_WECHAT_FIRST_THREE_TIMES_PER_DAY,
	SHARE_TWEET_BY_WECHAT_AFTER_THREE_TIMES_PER_DAY,
	PURCHASE_PRODUCTS,
	PAY_DEPOSIT_BY_FUNDS,
	PAY_DEPOSIT_BY_BROKERAGE,
	YIELD_INTEREST,
	WITHDRAW,
	LESSON_APPOINTMENT,
	CANCEL_LESSON_APPOINTMENT,
	CHECK_IN_AFTER_APPOINTMENT,
	CHECK_IN_WITHOUT_APPOINTMENT,
	BREAK_APPOINTMENT
	
}
