ALTER table chenkuserdb1.skt6 add COLUMN(dataStatus int DEFAULT 0);

CREATE 
or REPLACE
VIEW yiwu.`vcourse` AS
    SELECT 
        `chenkuserdb1`.`skt6`.`SKF50` AS `id`,
        `chenkuserdb1`.`skt6`.`SKF51` AS `name`,
        `chenkuserdb1`.`skt6`.`SKF52` AS `dance_id`,
        `chenkuserdb1`.`skt6`.`SKF53` AS `danceDesc`,
        `chenkuserdb1`.`skt6`.`SKF54` AS `store_id`,
        `chenkuserdb1`.`skt6`.`SKF55` AS `storeName`,
        `chenkuserdb1`.`skt6`.`SKF56` AS `teacher_id`,
        `chenkuserdb1`.`skt6`.`SKF57` AS `teacherName`,
        `chenkuserdb1`.`skt6`.`SKF58` AS `interval_id`,
        `chenkuserdb1`.`skt6`.`SKF59` AS `intervalDesc`,
        `chenkuserdb1`.`skt6`.`SKF60` AS `startTime`,
        `chenkuserdb1`.`skt6`.`SKF61` AS `endTime`,
        `chenkuserdb1`.`skt6`.`SKF62` AS `startDate`,
        `chenkuserdb1`.`skt6`.`SKF63` AS `endDate`,
        `chenkuserdb1`.`skt6`.`SKF64` AS `sumCourseHours`,
        `chenkuserdb1`.`skt6`.`SKF65` AS `classRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF66` AS `classRoomName`,
		dataStatus,
        `chenkuserdb1`.`skt6`.`SF_CREATE_USER` AS `sf_create_user`,
        `chenkuserdb1`.`skt6`.`SF_LAST_CHANGE_USER` AS `sf_last_change_user`,
        `chenkuserdb1`.`skt6`.`SF_CREATE_TIME` AS `sf_create_time`,
        `chenkuserdb1`.`skt6`.`SF_LAST_CHANGE_TIME` AS `sf_last_change_time`,
        `chenkuserdb1`.`skt6`.`MachineCode` AS `MachineCode`,
        `chenkuserdb1`.`skt6`.`Sf_Last_Sync_TimeStamp` AS `sf_last_sync_timeStamp`,
        `chenkuserdb1`.`skt6`.`SKF88` AS `weeklyCourseHours`,
        `chenkuserdb1`.`skt6`.`SKF89` AS `delete_flag`,
        `chenkuserdb1`.`skt6`.`SKF93` AS `weeks`,
        `chenkuserdb1`.`skt6`.`SKF118` AS `courseType`,
        `chenkuserdb1`.`skt6`.`SKF165` AS `monInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF166` AS `monRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF167` AS `tueInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF168` AS `tueRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF169` AS `wedInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF170` AS `wedRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF171` AS `thuInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF172` AS `thuRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF173` AS `friInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF174` AS `friRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF175` AS `satInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF176` AS `satRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF177` AS `sunInterval_id`,
        `chenkuserdb1`.`skt6`.`SKF178` AS `sunRoom_id`,
        `chenkuserdb1`.`skt6`.`SKF197` AS `status`,
        `chenkuserdb1`.`skt6`.`SKF224` AS `StudentCount`,
        `chenkuserdb1`.`skt6`.`SF_Last_Change_Timestamp` AS `sf_last_change_timeStamp`,
        `chenkuserdb1`.`skt6`.`SKF367` AS `include_holeday_flag`,
        `chenkuserdb1`.`skt6`.`SKF388` AS `DanceGrade`,
        `chenkuserdb1`.`skt6`.`SKF868` AS `ShenheRen`,
        `chenkuserdb1`.`skt6`.`SKF919` AS `connotation`,
        `chenkuserdb1`.`skt6`.`SKF920` AS `help`,
        `chenkuserdb1`.`skt6`.`SKF921` AS `briefIntroduction`,
        `chenkuserdb1`.`skt6`.`SKF922` AS `picture`,
        `chenkuserdb1`.`skt6`.`SKF923` AS `videoURL`,
        `chenkuserdb1`.`skt6`.`SKF924` AS `audio`,
        `chenkuserdb1`.`skt6`.`SKF925` AS `audioURL`,
        `chenkuserdb1`.`skt6`.`SKF949` AS `danceIntroduction`,
        `chenkuserdb1`.`skt6`.`SKF1034` AS `subCourseType`
    FROM
        `chenkuserdb1`.`skt6`;

ALTER table chenkuserdb1.skt7 add COLUMN(dataStatus int DEFAULT 0);


CREATE 
	or REPLACE
VIEW  yiwu.vlesson AS
    SELECT 
        `chenkuserdb1`.`skt7`.`SKF139` AS `id`,
        `chenkuserdb1`.`skt7`.`SKF120` AS `course_id`,
        `chenkuserdb1`.`skt7`.`SKF72` AS `lessonDate`,
        `chenkuserdb1`.`skt7`.`SKF73` AS `startTime`,
        `chenkuserdb1`.`skt7`.`SKF74` AS `endTime`,
        `chenkuserdb1`.`skt7`.`SKF75` AS `courseDesc`,
        `chenkuserdb1`.`skt7`.`SKF76` AS `storeId`,
        `chenkuserdb1`.`skt7`.`SKF77` AS `storeName`,
        `chenkuserdb1`.`skt7`.`SKF78` AS `lessonTime`,
        `chenkuserdb1`.`skt7`.`SKF79` AS `yindaoTeacherId`,
        `chenkuserdb1`.`skt7`.`SKF80` AS `yindaoTeacherName`,
        `chenkuserdb1`.`skt7`.`SKF81` AS `classRoomId`,
        `chenkuserdb1`.`skt7`.`SKF82` AS `classRoomName`,
        `chenkuserdb1`.`skt7`.`SKF221` AS `shidaoTeacherId`,
        `chenkuserdb1`.`skt7`.`SKF222` AS `shidaoTeacherName`,
        `chenkuserdb1`.`skt7`.`SKF200` AS `lessonStatus`,
        `chenkuserdb1`.`skt7`.`SKF336` AS `courseType`,
        `chenkuserdb1`.`skt7`.`SKF1035` AS `subCourseType`,
        `chenkuserdb1`.`skt7`.`SKF83` AS `flag_delete`,
        `chenkuserdb1`.`skt7`.`SKF198` AS `start_date_time`,
        `chenkuserdb1`.`skt7`.`SKF199` AS `lessonTime_minutes`,
        `chenkuserdb1`.`skt7`.`SKF368` AS `appointed_huijiheyue`,
        `chenkuserdb1`.`skt7`.`SKF821` AS `yindaoRenshu`,
        `chenkuserdb1`.`skt7`.`SKF822` AS `tiyanRenshu`,
        `chenkuserdb1`.`skt7`.`SKF823` AS `dianmingRenshu`,
        `chenkuserdb1`.`skt7`.`SKF824` AS `shidaoRenshu`,
        `chenkuserdb1`.`skt7`.`SKF826` AS `qiandaoRenshu`,
        `chenkuserdb1`.`skt7`.`SKF827` AS `yuyueRenshu`,
        `chenkuserdb1`.`skt7`.`SKF855` AS `neihan`,
        `chenkuserdb1`.`skt7`.`SKF856` AS `help`,
        `chenkuserdb1`.`skt7`.`SKF857` AS `jianjie`,
        `chenkuserdb1`.`skt7`.`SKF858` AS `picture`,
        `chenkuserdb1`.`skt7`.`SKF859` AS `video`,
        `chenkuserdb1`.`skt7`.`SKF860` AS `audio`,
        `chenkuserdb1`.`skt7`.`SKF861` AS `audio_link`,
        `chenkuserdb1`.`skt7`.`SKF950` AS `dance_introduction`,
        `chenkuserdb1`.`skt7`.`SKF1001` AS `QRcode`,
        dataStatus,
        `chenkuserdb1`.`skt7`.`SF_CREATE_USER` AS `sf_create_user`,
        `chenkuserdb1`.`skt7`.`SF_LAST_CHANGE_USER` AS `sf_last_change_user`,
        `chenkuserdb1`.`skt7`.`SF_CREATE_TIME` AS `sf_create_time`,
        `chenkuserdb1`.`skt7`.`SF_LAST_CHANGE_TIME` AS `sf_last_change_time`,
        `chenkuserdb1`.`skt7`.`MachineCode` AS `machineCode`,
        `chenkuserdb1`.`skt7`.`Sf_Last_Sync_TimeStamp` AS `sf_last_sync_timeStamp`,
        `chenkuserdb1`.`skt7`.`SF_Last_Change_Timestamp` AS `sf_last_change_timeStamp`
    FROM
        `chenkuserdb1`.`skt7`;
